Repository MyLittleWebServer/webserv, pull requests merged in 2023-06, with the labels that each got.

#13 feat(client): 클라이언트 소켓으로 송신 및 HTTP 요청 메시지 파싱
  .gitignore
  Client.cpp
  Client.hpp
  Clients/AMethod.cpp
  Clients/AMethod.hpp
  Clients/DELETE.cpp
  Clients/DELETE.hpp
  Clients/GET.cpp
  Clients/GET.hpp
  Clients/POST.cpp
  Clients/POST.hpp
  EventHandler.cpp
  EventHandler.hpp
  Makefile
  Server.cpp
  Server.hpp
  TDD/HTML.html
  Utils.cpp
Labels: enhancement

#14 style: update directory structure for better code organization
  .gitignore
  Makefile
  Makefile2
  docs/webserv.pseudo
  main.cpp
  srcs/clients/client/include/Client.hpp
  srcs/clients/client/src/Client.cpp
  srcs/clients/method/include/AMethod.hpp
  srcs/clients/method/include/DELETE.hpp
  srcs/clients/method/include/GET.hpp
  srcs/clients/method/include/POST.hpp
  srcs/clients/method/src/AMethod.cpp
  srcs/clients/method/src/DELETE.cpp
  srcs/clients/method/src/GET.cpp
  srcs/clients/method/src/POST.cpp
  srcs/main.cpp
  srcs/server/include/EventHandler.hpp
  srcs/server/include/Kqueue.hpp
  srcs/server/include/Server.hpp
  srcs/server/src/EventHandler.cpp
  srcs/server/src/Kqueue.cpp
  srcs/server/src/Server.cpp
  srcs/utils/util/include/Utils.hpp
  srcs/utils/util/src/Utils.cpp
  tests/YoupiBanane/Yeah/not_happy.bad_extension
  tests/YoupiBanane/nop/other.pouic
  tests/YoupiBanane/nop/youpi.bad_extension
  tests/YoupiBanane/put_test/index.html
  tests/YoupiBanane/youpi.bad_extension
  tests/YoupiBanane/youpi.bla
Labels: DevOps

#20 Configuration 개선
  srcs/config/child_config/include/IChildConfig.hpp
  srcs/config/child_config/location_config/include/ILocationConfig.hpp
  srcs/config/child_config/location_config/include/LocationConfig.hpp
  srcs/config/child_config/location_config/src/LocationConfig.cpp
  srcs/config/child_config/mime_types_config/include/MimeTypesConfig.hpp
  srcs/config/child_config/mime_types_config/src/MimeTypesConfig.cpp
  srcs/config/child_config/proxy_config/include/ProxyConfig.hpp
  srcs/config/child_config/proxy_config/src/ProxyConfig.cpp
  srcs/config/child_config/root_config/include/IRootConfig.hpp
  srcs/config/child_config/root_config/include/RootConfig.hpp
  srcs/config/child_config/root_config/src/RootConfig.cpp
  srcs/config/child_config/server_config/include/IServerConfig.hpp
  srcs/config/child_config/server_config/include/ServerConfig.hpp
  srcs/config/child_config/server_config/src/ServerConfig.cpp
  srcs/config/src/Config.cpp
Labels: enhancement

#24 23 configuration 버그 수정
  config/default.conf
  srcs/config/child_config/location_config/src/LocationConfig.cpp
  srcs/config/child_config/mime_types_config/src/MimeTypesConfig.cpp
  srcs/config/child_config/proxy_config/src/ProxyConfig.cpp
  srcs/config/child_config/root_config/src/RootConfig.cpp
  srcs/config/child_config/server_config/include/IServerConfig.hpp
  srcs/config/child_config/server_config/include/ServerConfig.hpp
  srcs/config/child_config/server_config/src/ServerConfig.cpp
Labels: bug

#31 fix(locationConfig): route err
  srcs/config/child_config/location_config/src/LocationConfig.cpp
Labels: bug
