Repository MyLittleWebServer/webserv, pull requests merged in 2023-07, with the labels that each got.

#46 43 response request 분리
  srcs/clients/candidate_fields/include/CandidateFields.hpp
  srcs/clients/candidate_fields/include/ICandidateFields.hpp
  srcs/clients/candidate_fields/srcs/CandidateFields.cpp
  srcs/clients/request/include/IRequest.hpp
  srcs/clients/request/include/Request.hpp
  srcs/clients/request/request_parser/include/IRequestParser.hpp
  srcs/clients/request/request_parser/include/RequestParser.hpp
  srcs/clients/request/request_parser/src/RequestParser.cpp
  srcs/clients/request/src/Request.cpp
  srcs/clients/response/include/IResponse.hpp
  srcs/clients/response/include/Response.hpp
  srcs/clients/response/src/Response.cpp
Labels: enhancement

#50 docs(Makefile): refact Make all directories inaudible
  Makefile
Labels: DevOps

#53 feat(socket): add setsockopt for reuseaddr
  srcs/server/src/Server.cpp
Labels: bug, enhancement

#59 51 refactorclient change client structure
  srcs/clients/request/include/Request.hpp
  srcs/clients/request/request_parser/include/IRequestParser.hpp
  srcs/clients/request/request_parser/include/RequestParser.hpp
  srcs/clients/request/request_parser/src/RequestParser.cpp
  srcs/clients/request/src/Request.cpp
  srcs/config/child_config/location_config/src/LocationConfig.cpp
Labels: enhancement

#75 63 feat cgi
  srcs/clients/cgi/include/CGI.hpp
  srcs/clients/cgi/include/ICGI.hpp
  srcs/clients/cgi/src/CGI.cpp
  srcs/clients/request/include/IRequest.hpp
  srcs/clients/request/include/Request.hpp
  srcs/clients/request/request_parser/include/IRequestParser.hpp
  srcs/clients/request/request_parser/src/RequestParser.cpp
  srcs/clients/request/src/Request.cpp
  srcs/exception/include/ExceptionThrower.hpp
  srcs/exception/include/errorMessage.hpp
  srcs/exception/src/ExceptionThrower.cpp
  srcs/server/include/Kqueue.hpp
  srcs/server/src/Kqueue.cpp
Labels: DevOps

#92 87 feateventhandler keep alive
  srcs/clients/client/include/Client.hpp
  srcs/clients/client/src/Client.cpp
  srcs/clients/request/include/IRequest.hpp
  srcs/clients/request/include/Request.hpp
  srcs/clients/request/src/Request.cpp
  srcs/clients/response/include/IResponse.hpp
  srcs/clients/response/include/Response.hpp
  srcs/clients/response/src/Response.cpp
  srcs/server/src/EventHandler.cpp
Labels: DevOps

#97 fix(errorPage): fix relative path to absolute path
  tests/html/400.html
  tests/html/403.html
  tests/html/404.html
  tests/html/405.html
  tests/html/408.html
  tests/html/409.html
  tests/html/500.html
  tests/html/501.html
  tests/html/index.html
Labels: bug

#102 101 fixrequestparser advance parsing complete logic
  srcs/clients/request/request_parser/include/RequestParser.hpp
  srcs/clients/request/request_parser/src/RequestParser.cpp
Labels: bug

#94 93 fixeventhandler process down when client close socket connection
  srcs/clients/client/include/Client.hpp
  srcs/clients/client/src/Client.cpp
  srcs/main.cpp
  srcs/server/src/EventHandler.cpp
Labels: bug

#100 95 fixcgi cgi execute error
  srcs/clients/cgi/src/CGI.cpp
  srcs/clients/response/src/Response.cpp
  srcs/utils/util/include/Utils.hpp
  srcs/utils/util/include/Utils.tpp
  srcs/utils/util/src/Utils.cpp
Labels: bug

#112 fix: heap use after free error on timeout
  srcs/clients/client/src/Client.cpp
  srcs/server/src/EventHandler.cpp
Labels: bug

#114 fix(EventHandler): fix heap use after free
  srcs/clients/client/include/Client.hpp
  srcs/clients/client/src/Client.cpp
  srcs/clients/response/include/IResponse.hpp
  srcs/clients/response/include/Response.hpp
  srcs/clients/response/src/Response.cpp
  srcs/server/src/EventHandler.cpp
Labels: bug

#108 107 feat rfc7230 3 message format
  config/proxy.conf
  srcs/clients/client/include/Client.hpp
  srcs/clients/client/src/Client.cpp
  srcs/clients/request/include/IRequest.hpp
  srcs/clients/request/include/Request.hpp
  srcs/clients/request/request_parser/include/RequestParser.hpp
  srcs/clients/request/request_parser/src/RequestParser.cpp
  srcs/clients/request/src/Request.cpp
  srcs/server/src/EventHandler.cpp
  srcs/utils/util/include/Status.hpp
  srcs/utils/util/include/Utils.hpp
  srcs/utils/util/include/Utils.tpp
  srcs/utils/util/src/Status.cpp
  srcs/utils/util/src/Utils.cpp
Labels: enhancement

#119 RFC 7230 4. Transfer Encoding
  srcs/clients/candidate_fields/srcs/CandidateFields.cpp
  srcs/clients/request/request_parser/include/RequestParser.hpp
  srcs/clients/request/request_parser/src/RequestParser.cpp
Labels: enhancement

#124 feat: implement redirection
  config/default.conf
  srcs/clients/client/include/Client.hpp
  srcs/clients/client/src/Client.cpp
  srcs/clients/request/request_parser/include/RequestParser.hpp
  srcs/clients/request/request_parser/src/RequestParser.cpp
  srcs/clients/response/include/Response.hpp
  srcs/clients/response/src/Response.cpp
  srcs/server/src/EventHandler.cpp
Labels: enhancement

#126 feat(DELETE): implement delete method
  srcs/clients/method/src/DELETE.cpp
  srcs/clients/request/request_parser/src/RequestParser.cpp
Labels: enhancement

#128 feat(POST): add location headerfield into response
  config/default.conf
  srcs/clients/method/src/POST.cpp
Labels: enhancement

#131 feat(requestParser): rfc-7230-9-Security Considerations
  config/proxy.conf
  srcs/clients/request/request_parser/include/RequestParser.hpp
  srcs/clients/request/request_parser/src/RequestParser.cpp
Labels: enhancement

#136 feat(POST): upload multiple-form/data
  srcs/clients/method/src/POST.cpp
Labels: enhancement

#135 fix(Utils): fix underflow in ft_trim
  srcs/utils/util/src/Utils.cpp
Labels: bug

#122 refactor: client
  srcs/clients/client/include/Client.hpp
  srcs/clients/client/src/Client.cpp
  srcs/server/src/EventHandler.cpp
Labels: refactoring

#138 fix(response): fix redirection towards default location
  .gitignore
  srcs/clients/response/include/Response.hpp
  srcs/clients/response/src/Response.cpp
Labels: bug

#147 feat(POST): create file w/ content-type
  srcs/clients/method/src/POST.cpp
Labels: enhancement

#151 docs(.git): add git features
  .gitattributes
  README.md
  tests/html/asset/git/sige-test.png
Labels: documentation, DevOps

#153 test: files
  tests/html/400.html
  tests/html/403.html
  tests/html/404.html
  tests/html/405.html
  tests/html/408.html
  tests/html/409.html
  tests/html/500.html
  tests/html/501.html
  tests/html/asset/css/error-page.css
  tests/html/asset/css/index.css
  tests/html/asset/css/login.css
  tests/html/index.html
  tests/html/login.html
  tests/html/test.html
Labels: DevOps

#132 feat(develop): rfc-7231-3-Representations
  srcs/clients/request/request_parser/include/RequestParser.hpp
  srcs/clients/request/request_parser/src/RequestParser.cpp
Labels: enhancement

#149 fix(EventHandler): fix event() error in Kqueue::deleteEvent
  srcs/clients/client/include/Client.hpp
  srcs/clients/client/src/Client.cpp
  srcs/server/include/EventHandler.hpp
  srcs/server/include/Kqueue.hpp
  srcs/server/src/EventHandler.cpp
  srcs/server/src/Kqueue.cpp
Labels: bug

#154 refactor(POST): remove 'this' and some minor changes
  srcs/clients/method/include/POST.hpp
  srcs/clients/method/src/POST.cpp
Labels: refactoring

#143 feat: RFC 7231 4 Request Methods
  Makefile
  srcs/clients/client/include/Client.hpp
  srcs/clients/client/src/Client.cpp
  srcs/clients/method/include/GET.hpp
  srcs/clients/method/include/HEAD.hpp
  srcs/clients/method/include/IMethod.hpp
  srcs/clients/method/include/OPTIONS.hpp
  srcs/clients/method/src/HEAD.cpp
  srcs/clients/method/src/OPTIONS.cpp
  srcs/clients/request/request_parser/include/RequestParser.hpp
  srcs/clients/request/request_parser/src/RequestParser.cpp
  srcs/server/src/EventHandler.cpp
Labels: enhancement

#166 fix: fix compile error
  srcs/server/src/EventHandler.cpp
  srcs/server/src/Kqueue.cpp
  srcs/server/src/Server.cpp
  srcs/utils/util/src/Utils.cpp
Labels: bug

#157 156 feat rfc7231 5 request header fields 6 Response Status Codes
  srcs/clients/candidate_fields/include/CandidateFields.hpp
  srcs/clients/candidate_fields/srcs/CandidateFields.cpp
  srcs/clients/client/include/Client.hpp
  srcs/clients/client/src/Client.cpp
  srcs/clients/method/src/GET.cpp
  srcs/clients/method/src/HEAD.cpp
  srcs/clients/method/src/OPTIONS.cpp
  srcs/clients/request/include/IRequest.hpp
  srcs/clients/request/include/Request.hpp
  srcs/clients/request/request_parser/include/IRequestParser.hpp
  srcs/clients/request/request_parser/include/RequestParser.hpp
  srcs/clients/request/request_parser/src/RequestParser.cpp
  srcs/clients/request/src/Request.cpp
  srcs/clients/response/src/Response.cpp
  srcs/config/child_config/mime_types_config/include/MimeTypesConfig.hpp
  srcs/config/child_config/mime_types_config/src/MimeTypesConfig.cpp
  srcs/server/src/EventHandler.cpp
  srcs/utils/util/include/Status.hpp
  srcs/utils/util/include/Utils.hpp
  srcs/utils/util/include/Utils.tpp
  srcs/utils/util/src/Status.cpp
  srcs/utils/util/src/Utils.cpp
Labels: bug, enhancement

#169 feat: connection timeout
  config/default.conf
  srcs/clients/client/include/Client.hpp
  srcs/clients/client/src/Client.cpp
  srcs/config/child_config/server_config/include/IServerConfig.hpp
  srcs/config/child_config/server_config/include/ServerConfig.hpp
  srcs/config/child_config/server_config/src/ServerConfig.cpp
  srcs/config/include/Config.hpp
  srcs/config/include/IConfig.hpp
  srcs/config/src/Config.cpp
  srcs/server/include/EventHandler.hpp
  srcs/server/src/EventHandler.cpp
  srcs/utils/util/include/Utils.hpp
  srcs/utils/util/src/Utils.cpp
Labels: enhancement

#175 feat(post): create file w/ unique ID
  srcs/clients/method/include/POST.hpp
  srcs/clients/method/src/POST.cpp
Labels: enhancement

#178 feat(put): implement put method
  srcs/clients/client/src/Client.cpp
  srcs/clients/method/include/PUT.hpp
  srcs/clients/method/src/PUT.cpp
  srcs/clients/request/request_parser/src/RequestParser.cpp
  srcs/utils/util/include/Status.hpp
  srcs/utils/util/src/Status.cpp
Labels: enhancement

#188 docs(418): add 418 error page and images
  tests/html/418.html
  tests/html/asset/waifu.jpeg
Labels: enhancement

#194 fix(POST): add location field for response
  srcs/clients/method/include/POST.hpp
  srcs/clients/method/src/POST.cpp
Labels: bug

#202 docs(Method): apply doxygen
  Makefile
  srcs/clients/client/src/Client.cpp
  srcs/clients/method/include/DummyMethod.hpp
  srcs/clients/method/include/PUT.hpp
  srcs/clients/method/src/DELETE.cpp
  srcs/clients/method/src/DummyMethod.cpp
  srcs/clients/method/src/HEAD.cpp
  srcs/clients/method/src/OPTIONS.cpp
  srcs/clients/method/src/POST.cpp
  srcs/clients/method/src/PUT.cpp
Labels: documentation

#209 fix(EventHandler): invalid logger msg
  srcs/clients/request/request_parser/src/RequestParser.cpp
  srcs/server/src/EventHandler.cpp
Labels: bug
